import json
import urllib.request
import urllib.error
from typing import Dict, Any, List, Optional

from aicli.config import config


import threading

class VideoTaggerService:
    """High-level Orchestrator for video metadata generation via LM Studio."""
    
    VIDEO_EXTENSIONS = {".mp4", ".mkv", ".mov", ".avi", ".webm", ".m4v", ".ts", ".mts"}
    _lm_lock = threading.Lock()

    @staticmethod
    def ask_lmstudio(clips: List[Dict[str, Any]], path_hint: str) -> Optional[Dict[str, Any]]:
        transcript = "\n".join(
            f"[{int(c['start_sec']//60)}m{int(c['start_sec']%60)}s] {c['text']}"
            for c in clips
        )

        system = """You are a highly efficient JSON data-extraction engine.
You extract structured metadata from raw video transcripts.
CRUCIAL: Output ONLY a valid JSON object. No markdown, no preambles, no "Thinking Process", no explanations.

Schema:
{
  "title": "<Generate a concise, highly accurate descriptive title for the lecture (max 60 chars)>",
  "filename": "<Generate a clean, human-readable filename in Title Case with spaces (e.g. 'Nuclear Energy Fission and Fusion'), max 50 chars, NO hyphens, NO underscores>",
  "lesson_number": <Analyze the provided Folder/Filename hint. Intelligently extract the ACTUAL chronological lesson, class, or sequence number (ignore long random ID prefixes like 1995382323). Output as a simple integer (e.g., if 'L66' or '056' is in the name, output 66 or 56). If uncertain, output 999.>,
  "subject": "<Determine the academic subject (e.g. Physics, History, Math)>",
  "topics": ["<topic1>", "<topic2>", "<topic3>"],
  "description": "<Generate a 2-3 sentence summary of the core concepts taught>",
  "teacher": "<Extract the name of the teacher or professor (if mentioned, else 'Unknown')>",
  "coaching": "<Extract the coaching institute or channel name (if mentioned, else 'Unknown')>",
  "language": "<Determine spoken language (e.g. hin, eng)>"
}"""

        payload = json.dumps({
            "model": config.model_name,
            "system_prompt": system,
            "input": f"Folder: {path_hint}\n\nTranscript Snippet:\n{transcript[:4000]}\n\nGenerate JSON now.",
            "temperature": 0.1,
            "max_output_tokens": 500,
            "stream": False
        }).encode()

        # Switch from legacy OpenAI endpoint to native LM Studio v1 REST API
        base_idx = config.lm_studio_base_url.rfind('/v1')
        endpoint = config.lm_studio_base_url[:base_idx] + "/api/v1/chat" if base_idx != -1 else f"{config.lm_studio_base_url}/chat"
        
        req = urllib.request.Request(
            endpoint,
            data=payload,
            headers={
                "Content-Type": "application/json",
                "Authorization": f"Bearer {config.lm_studio_api_key}"
            },
            method="POST"
        )
        try:
            with urllib.request.urlopen(req, timeout=120) as resp:
                raw_response = resp.read()
                data = json.loads(raw_response)
                
                # Native v1 API output parsing
                if "output" in data and len(data["output"]) > 0:
                    text = data["output"][0].get("content", "").strip()
                else:
                    text = ""
                
                # Resilient extraction of JSON block from conversational fluff
                import re
                match = re.search(r'(\{.*\})', text, re.DOTALL)
                if match:
                    text = match.group(1)
                
                if not text:
                    raise ValueError("Empty response generated by LLM")
                    
                return json.loads(text)
        except urllib.error.URLError as e:
            raise ConnectionError(f"LM Studio Error: {e}")
        except Exception as e:
            raw = text if 'text' in locals() and text else "<EMPTY STRING>"
            raise ValueError(f"Failed to parse response. Error: {e}. Raw Text: '{raw[:200]}'")

    @staticmethod
    def global_course_sort(videos: List[Dict[str, Any]]) -> List[str]:
        """
        Pass filenames to LM Studio for intelligent chronological ordering.
        """
        system = """You are an elite academic curriculum sequencer.
Given an unordered list of lecture video filenames, sort them into the correct chronological course order.
Use lesson numbers, unit numbers, part numbers, and topic progression to determine the correct sequence.

RULES:
- Output ONLY a valid JSON array of the EXACT input strings, reordered.
- Do NOT alter any string. Return them exactly as given.
- No markdown, no explanation, no preamble. Just the JSON array."""
        
        # Send just the filename strings — fast and reliable
        filenames = [v["path"] for v in videos]
        
        payload = json.dumps({
            "model": config.model_name,
            "system_prompt": system,
            "input": json.dumps(filenames, indent=1) + "\n\nSort these filenames chronologically. Output the JSON array now:",
            "temperature": 0.0,
            "max_output_tokens": 8000,
            "stream": False
        }).encode()

        base_idx = config.lm_studio_base_url.rfind('/v1')
        endpoint = config.lm_studio_base_url[:base_idx] + "/api/v1/chat" if base_idx != -1 else f"{config.lm_studio_base_url}/chat"
        
        req = urllib.request.Request(
            endpoint,
            data=payload,
            headers={
                "Content-Type": "application/json",
                "Authorization": f"Bearer {config.lm_studio_api_key}"
            },
            method="POST"
        )
        
        try:
            with urllib.request.urlopen(req, timeout=300) as resp:
                data = json.loads(resp.read())
                if "output" in data and len(data["output"]) > 0:
                    text = data["output"][0].get("content", "").strip()
                else:
                    raise ValueError("Empty output")
                    
                import re
                match = re.search(r'(\[.*\])', text, re.DOTALL)
                if match:
                    text = match.group(1)
                    
                sorted_ids = json.loads(text)
                if not isinstance(sorted_ids, list):
                    raise ValueError("LLM returned non-array structure for sorting.")
                return sorted_ids
        except Exception as e:
            raise RuntimeError(f"LLM global sort failed: {e}") from e
