import json
import urllib.request
import urllib.error
from pathlib import Path
from typing import Dict, Any, List, Optional

from aicli.config import config


import threading


class VideoTaggerService:
    """High-level Orchestrator for video metadata generation via Ollama."""

    VIDEO_EXTENSIONS = {".mp4", ".mkv", ".mov", ".avi", ".webm", ".m4v", ".ts", ".mts"}
    _lm_lock = threading.Lock()

    @staticmethod
    def ask_ollama(
        clips: List[Dict[str, Any]], path_hint: str
    ) -> Optional[Dict[str, Any]]:
        transcript = "\n".join(
            f"[{int(c['start_sec'] // 60)}m{int(c['start_sec'] % 60)}s] {c['text']}"
            for c in clips
        )

        system = """You are a highly efficient JSON data-extraction engine.
You extract structured metadata from raw video transcripts.
CRUCIAL: Output ONLY a valid JSON object. No markdown, no preambles, no "Thinking Process", no explanations.

Schema:
{
  "title": "<Generate a concise, highly accurate descriptive title for the lecture (max 60 chars)>",
  "filename": "<Generate a clean, human-readable filename in Title Case with spaces (e.g. 'Nuclear Energy Fission and Fusion'), max 50 chars, NO hyphens, NO underscores>",
  "lesson_number": <Analyze the provided Folder/Filename hint. Intelligently extract the ACTUAL chronological lesson, class, or sequence number (ignore long random ID prefixes like 1995382323). Output as a simple integer (e.g., if 'L66' or '056' is in the name, output 66 or 56). If uncertain, output 999.>,
  "subject": "<Determine the academic subject (e.g. Physics, History, Math)>",
  "topics": ["<topic1>", "<topic2>", "<topic3>"],
  "description": "<Generate a 2-3 sentence summary of the core concepts taught>",
  "teacher": "<Extract the name of the teacher or professor (if mentioned, else 'Unknown')>",
  "coaching": "<Extract the coaching institute or channel name (if mentioned, else 'Unknown')>",
  "language": "<Determine spoken language (e.g. hin, eng)>"
}"""

        payload = json.dumps(
            {
                "model": config.model_name,
                "messages": [
                    {"role": "system", "content": system},
                    {
                        "role": "user",
                        "content": f"Folder: {path_hint}\n\nTranscript Snippet:\n{transcript[:4000]}\n\nGenerate JSON now.",
                    },
                ],
                "temperature": 0.1,
                "max_tokens": 500,
                "stream": False,
            }
        ).encode()

        endpoint = f"{config.ollama_base_url}/api/chat"

        req = urllib.request.Request(
            endpoint,
            data=payload,
            headers={"Content-Type": "application/json"},
            method="POST",
        )
        try:
            with urllib.request.urlopen(req, timeout=120) as resp:
                raw_response = resp.read()
                data = json.loads(raw_response)

                if "message" in data and data["message"]:
                    text = data["message"].get("content", "").strip()
                else:
                    text = ""

                import re

                match = re.search(r"(\{.*\})", text, re.DOTALL)
                if match:
                    text = match.group(1)

                if not text:
                    raise ValueError("Empty response generated by LLM")

                return json.loads(text)
        except urllib.error.URLError as e:
            raise ConnectionError(f"Ollama Error: {e}")
        except Exception as e:
            raw = text if "text" in locals() and text else "<EMPTY STRING>"
            raise ValueError(
                f"Failed to parse response. Error: {e}. Raw Text: '{raw[:200]}'"
            )

    @staticmethod
    def global_course_sort(videos: List[Dict[str, Any]]) -> List[str]:
        """
        Pass filenames to Ollama for intelligent chronological ordering.
        Uses numeric IDs to minimize token count.
        """
        system = """You are an academic curriculum sequencer.
Given a numbered list of lecture video filenames, output their IDs sorted in correct chronological course order.
Use lesson numbers (L02, L23, LESSON_12), unit numbers (UNIT_1, unit-8), and part numbers to determine sequence.

OUTPUT: A JSON array of the integer IDs in correct order. Example: [3, 1, 0, 2]
No markdown, no explanation. Just the JSON array."""

        filenames = [v["path"] for v in videos]

        numbered = "\n".join(f"{i}: {Path(f).stem}" for i, f in enumerate(filenames))

        payload = json.dumps(
            {
                "model": config.model_name,
                "messages": [
                    {"role": "system", "content": system},
                    {
                        "role": "user",
                        "content": f"{numbered}\n\nSort by ID. Output JSON array:",
                    },
                ],
                "temperature": 0.0,
                "max_tokens": 2000,
                "stream": False,
            }
        ).encode()

        endpoint = f"{config.ollama_base_url}/api/chat"

        req = urllib.request.Request(
            endpoint,
            data=payload,
            headers={"Content-Type": "application/json"},
            method="POST",
        )

        try:
            with urllib.request.urlopen(req, timeout=300) as resp:
                data = json.loads(resp.read())
                if "message" in data and data["message"]:
                    text = data["message"].get("content", "").strip()
                else:
                    raise ValueError("Empty output")

                import re

                match = re.search(r"(\[.*\])", text, re.DOTALL)
                if match:
                    text = match.group(1)

                numbers = re.findall(r"\d+", text)
                sorted_indices = [int(n) for n in numbers]
                if not sorted_indices:
                    raise ValueError(
                        f"LLM did not return any valid numbers. Raw: {text}"
                    )

                return [
                    filenames[int(i)]
                    for i in sorted_indices
                    if 0 <= int(i) < len(filenames)
                ]
        except Exception as e:
            raise RuntimeError(f"LLM global sort failed: {e}") from e
