import type { WorkflowDefinition } from "../types";
import { codexWorkflowDefinitions } from "./codex";

export const workflowCategories = ["Study", "Codex", "Documents", "Images", "Audio", "Video", "News"];

export const workflowDefinitions: WorkflowDefinition[] = [
  {
    id: "recall",
    category: "Study",
    label: "Recall",
    endpoint: "/api/workflows/recall/run",
    fields: [
      { type: "providerModel" },
      { type: "textarea", id: "notes", label: "Notes", rows: 12, placeholder: "Paste UPSC notes..." },
    ],
    buildPayload: (values) => ({
      provider_id: values.provider_id,
      model: values.model,
      notes: values.notes,
    }),
  },
  ...codexWorkflowDefinitions,
  {
    id: "ocr-run",
    category: "Documents",
    label: "OCR: ZIP images to Markdown",
    endpoint: "/api/workflows/ocr/run",
    fields: [
      { type: "providerModel" },
      { type: "path", id: "path", label: "Input ZIP file" },
      { type: "number", id: "render_workers", label: "Render workers", min: 1, max: 64, default: 2 },
      { type: "number", id: "workers", label: "OCR workers", min: 1, max: 64, default: 1 },
    ],
    buildPayload: (values) => ({
      provider_id: values.provider_id,
      model: values.model,
      path: values.path,
      render_workers: values.render_workers,
      workers: values.workers,
    }),
  },
  {
    id: "ocr-pdf",
    category: "Documents",
    label: "OCR: PDF to Markdown",
    endpoint: "/api/workflows/ocr/pdf",
    fields: [
      { type: "providerModel" },
      { type: "path", id: "path", label: "Input PDF file" },
      { type: "number", id: "render_workers", label: "Render workers", min: 1, max: 64, default: 2 },
      { type: "number", id: "workers", label: "OCR workers", min: 1, max: 64, default: 1 },
    ],
    buildPayload: (values) => ({
      provider_id: values.provider_id,
      model: values.model,
      path: values.path,
      render_workers: values.render_workers,
      workers: values.workers,
    }),
  },
  {
    id: "analyze",
    category: "Documents",
    label: "Analyze: PDF report",
    endpoint: "/api/workflows/analyze/run",
    fields: [
      { type: "providerModel" },
      { type: "path", id: "path", label: "Input PDF file" },
      { type: "number", id: "render_workers", label: "Render workers", min: 1, max: 64, default: 2 },
      { type: "number", id: "workers", label: "OCR workers", min: 1, max: 64, default: 1 },
    ],
    buildPayload: (values) => ({
      provider_id: values.provider_id,
      model: values.model,
      path: values.path,
      render_workers: values.render_workers,
      workers: values.workers,
    }),
  },
  {
    id: "image-run",
    category: "Images",
    label: "Analyze image",
    endpoint: "/api/workflows/image/run",
    fields: [
      { type: "providerModel" },
      { type: "path", id: "path", label: "Input image" },
      {
        type: "select",
        id: "mode",
        label: "Mode",
        default: "",
        options: [
          { value: "", label: "Default (safe rename)" },
          { value: "rename", label: "Rename" },
          { value: "junk", label: "Junk classification" },
          { value: "digitize", label: "Digitize text" },
        ],
      },
    ],
    buildPayload: (values) => ({
      provider_id: values.provider_id,
      model: values.model,
      path: values.path,
      mode: values.mode || "",
    }),
  },
  {
    id: "image-rename",
    category: "Images",
    label: "Safe image rename",
    endpoint: "/api/workflows/image/rename",
    fields: [
      { type: "providerModel" },
      { type: "path", id: "path", label: "Input image" },
      { type: "checkbox", id: "apply", label: "Apply rename", checked: false },
    ],
    buildPayload: (values) => ({
      provider_id: values.provider_id,
      model: values.model,
      path: values.path,
      apply: Boolean(values.apply),
    }),
  },
  {
    id: "image-prune-refs",
    category: "Images",
    label: "Prune stale refs",
    endpoint: "/api/workflows/image/prune-refs",
    fields: [
      { type: "path", id: "markdown_path", label: "Markdown file" },
      { type: "path", id: "asset_dir", label: "Asset directory" },
      { type: "checkbox", id: "apply", label: "Apply filesystem changes", checked: false },
    ],
    buildPayload: (values) => ({
      markdown_path: values.markdown_path,
      asset_dir: values.asset_dir,
      apply: Boolean(values.apply),
    }),
  },
  {
    id: "audio-transcribe",
    category: "Audio",
    label: "Transcribe",
    endpoint: "/api/workflows/audio/transcribe",
    fields: [
      { type: "path", id: "path", label: "Input audio file" },
      { type: "text", id: "model", label: "Whisper model", value: "large-v3", placeholder: "large-v3" },
    ],
    buildPayload: (values) => ({
      model: values.model,
      path: values.path,
    }),
  },
  {
    id: "audio-analyze",
    category: "Audio",
    label: "Analyze tracks",
    endpoint: "/api/workflows/audio/analyze",
    fields: [
      { type: "providerModel" },
      { type: "textarea", id: "transcript", label: "Transcript", rows: 10, placeholder: "Paste transcript(s), separated by blank line delimiter `---`" },
    ],
    buildPayload: (values) => ({
      provider_id: values.provider_id,
      model: values.model,
      track_text: typeof values.transcript === "string" ? values.transcript.split("\n---\n").map((text) => text.trim()).filter(Boolean) : [],
      track_names: [],
    }),
  },
  {
    id: "video-course",
    category: "Video",
    label: "Course folder",
    endpoint: "/api/workflows/video/course",
    fields: [
      { type: "path", id: "path", label: "Course source folder", picker: "directory" },
      { type: "text", id: "whisper_model", label: "Whisper model", value: "large-v3", placeholder: "large-v3" },
      { type: "text", id: "whisper_device", label: "Whisper device", value: "cuda", placeholder: "cuda" },
      { type: "number", id: "transcript_workers", label: "Transcription workers", min: 1, max: 6, default: 2 },
      { type: "number", id: "compression_workers", label: "Compression workers", min: 1, max: 6, default: 4 },
      { type: "checkbox", id: "skip_unreadable", label: "Skip unreadable videos", checked: false },
      { type: "number", id: "max_merge_hours", label: "Max hours per output video", min: 1, max: 24, default: 9 },
    ],
    buildPayload: (values) => ({
      path: values.path,
      whisper_model: values.whisper_model || "large-v3",
      whisper_device: values.whisper_device || "cuda",
      preset: "slideshow",
      resolution: 0,
      crf: 0,
      fps: "1/2",
      transcript_workers: values.transcript_workers || 2,
      compression_workers: values.compression_workers || 4,
      skip_unreadable: Boolean(values.skip_unreadable),
      max_merge_hours: values.max_merge_hours || 9,
      fast_skip: true,
    }),
  },
  {
    id: "video-generate",
    category: "Video",
    label: "Video notes/tags/course",
    endpoint: "/api/workflows/video/generate",
    fields: [
      { type: "providerModel" },
      { type: "text", id: "title", label: "Video title", value: "", placeholder: "Untitled video" },
      { type: "textarea", id: "transcript", label: "Transcript", rows: 14, placeholder: "Paste or generate transcript text..." },
      {
        type: "select",
        id: "mode",
        label: "Output mode",
        default: "notes",
        options: [
          { value: "notes", label: "Notes" },
          { value: "tags", label: "Tags" },
          { value: "course", label: "Course" },
        ],
      },
    ],
    buildPayload: (values) => ({
      provider_id: values.provider_id,
      model: values.model,
      title: values.title,
      transcript: values.transcript,
      mode: values.mode || "notes",
    }),
  },
  {
    id: "video-info",
    category: "Video",
    label: "Info",
    endpoint: "/api/workflows/video/info",
    fields: [{ type: "path", id: "path", label: "Input video file" }],
    buildPayload: (values) => ({ path: values.path }),
  },
  {
    id: "video-compress",
    category: "Video",
    label: "Compress",
    endpoint: "/api/workflows/video/compress",
    fields: [
      { type: "path", id: "path", label: "Input video file" },
      { type: "path", id: "output", label: "Output video file (optional)" },
      {
        type: "select",
        id: "preset",
        label: "Compression preset",
        default: "light",
        options: [
          { value: "ultralight", label: "Ultralight" },
          { value: "light", label: "Light" },
          { value: "balanced", label: "Balanced" },
          { value: "slideshow", label: "Slideshow" },
        ],
      },
      { type: "number", id: "resolution", label: "Resolution", min: 0, max: 1080, default: 240 },
      { type: "number", id: "crf", label: "NVENC CQ quality (optional)", min: 0, max: 51, default: 0 },
      { type: "text", id: "fps", label: "Frame rate override (optional)", value: "", placeholder: "15" },
      { type: "checkbox", id: "fast_skip", label: "Fast keyframe skip", checked: false },
    ],
    buildPayload: (values) => ({
      path: values.path,
      output: values.output,
      crf: values.crf,
      preset: values.preset || "light",
      resolution: values.resolution,
      fps: values.fps,
      fast_skip: Boolean(values.fast_skip),
    }),
  },
  {
    id: "video-backup",
    category: "Video",
    label: "Metadata backup",
    endpoint: "/api/workflows/video/metadata/backup",
    fields: [
      { type: "path", id: "path", label: "Input video file" },
      { type: "path", id: "sidecar", label: "Sidecar file (optional)" },
    ],
    buildPayload: (values) => ({ path: values.path, sidecar: values.sidecar, output: "" }),
  },
  {
    id: "video-restore",
    category: "Video",
    label: "Metadata restore",
    endpoint: "/api/workflows/video/metadata/restore",
    fields: [
      { type: "path", id: "path", label: "Input video file" },
      { type: "path", id: "sidecar", label: "Sidecar file" },
      { type: "path", id: "output", label: "Output video file (optional)" },
    ],
    buildPayload: (values) => ({ path: values.path, sidecar: values.sidecar, output: values.output }),
  },
  {
    id: "news",
    category: "News",
    label: "Analyze news feed",
    endpoint: "/api/workflows/news/run",
    fields: [
      { type: "providerModel" },
      { type: "path", id: "path", label: "Input JSON/XLSX file" },
      { type: "path", id: "output_path", label: "Output XLSX (optional)" },
      { type: "checkbox", id: "use_llm", label: "Use LLM summary", checked: true },
    ],
    buildPayload: (values) => ({
      provider_id: values.provider_id,
      model: values.model,
      path: values.path,
      output_path: values.output_path,
      use_llm: Boolean(values.model) && Boolean(values.use_llm),
    }),
  },
];
