import type { WorkflowDefinition } from "../types";
import { pathPayload, providerModelField, providerModelPayload } from "./builders";

export const videoWorkflowDefinitions: WorkflowDefinition[] = [
  {
    id: "video-course",
    category: "Video",
    label: "Course folder",
    endpoint: "/api/workflows/video/course",
    fields: [
      { type: "path", id: "path", label: "Course source folder", picker: "directory" },
      { type: "text", id: "whisper_model", label: "Whisper model", value: "large-v3", placeholder: "large-v3" },
      { type: "text", id: "whisper_device", label: "Whisper device", value: "cuda", placeholder: "cuda" },
      { type: "text", id: "output_name", label: "Course output name", value: "", placeholder: "Uses source folder name" },
      { type: "number", id: "transcript_workers", label: "Transcription workers (0 = auto)", min: 0, default: 0 },
      { type: "number", id: "compression_workers", label: "Compression workers (0 = auto)", min: 0, default: 0 },
      { type: "checkbox", id: "skip_unreadable", label: "Skip unreadable videos", checked: false },
      { type: "checkbox", id: "cleanup_verified_parts", label: "Delete source/cache after verified Course part", checked: false },
      { type: "number", id: "max_merge_hours", label: "Max hours per output video", min: 1, max: 24, default: 9 },
    ],
    buildPayload: (values) => ({
      path: values.path,
      whisper_model: values.whisper_model || "large-v3",
      whisper_device: values.whisper_device || "cuda",
      output_name: values.output_name,
      preset: "slideshow",
      resolution: 0,
      crf: 0,
      fps: "1/2",
      transcript_workers: values.transcript_workers || 0,
      compression_workers: values.compression_workers || 0,
      skip_unreadable: Boolean(values.skip_unreadable),
      cleanup_verified_parts: Boolean(values.cleanup_verified_parts),
      max_merge_hours: values.max_merge_hours || 9,
      fast_skip: true,
    }),
  },
  {
    id: "video-generate",
    category: "Video",
    label: "Video notes/tags/course",
    endpoint: "/api/workflows/video/generate",
    fields: [
      providerModelField,
      { type: "text", id: "title", label: "Video title", value: "", placeholder: "Untitled video" },
      { type: "textarea", id: "transcript", label: "Transcript", rows: 14, placeholder: "Paste or generate transcript text..." },
      {
        type: "select",
        id: "mode",
        label: "Output mode",
        default: "notes",
        options: [
          { value: "notes", label: "Notes" },
          { value: "tags", label: "Tags" },
          { value: "course", label: "Course" },
        ],
      },
    ],
    buildPayload: (values) => ({
      ...providerModelPayload(values),
      title: values.title,
      transcript: values.transcript,
      mode: values.mode || "notes",
    }),
  },
  {
    id: "video-info",
    category: "Video",
    label: "Info",
    endpoint: "/api/workflows/video/info",
    fields: [{ type: "path", id: "path", label: "Input video file" }],
    buildPayload: pathPayload,
  },
  {
    id: "video-compress",
    category: "Video",
    label: "Compress",
    endpoint: "/api/workflows/video/compress",
    fields: [
      { type: "path", id: "path", label: "Input video file" },
      { type: "path", id: "output", label: "Output video file (optional)" },
      {
        type: "select",
        id: "preset",
        label: "Compression preset",
        default: "light",
        options: [
          { value: "ultralight", label: "Ultralight" },
          { value: "light", label: "Light" },
          { value: "balanced", label: "Balanced" },
          { value: "slideshow", label: "Slideshow" },
        ],
      },
      { type: "number", id: "resolution", label: "Resolution", min: 0, max: 1080, default: 240 },
      { type: "number", id: "crf", label: "NVENC CQ quality (optional)", min: 0, max: 51, default: 0 },
      { type: "text", id: "fps", label: "Frame rate override (optional)", value: "", placeholder: "15" },
      { type: "checkbox", id: "fast_skip", label: "Fast keyframe skip", checked: false },
    ],
    buildPayload: (values) => ({
      path: values.path,
      output: values.output,
      crf: values.crf,
      preset: values.preset || "light",
      resolution: values.resolution,
      fps: values.fps,
      fast_skip: Boolean(values.fast_skip),
    }),
  },
  {
    id: "video-backup",
    category: "Video",
    label: "Metadata backup",
    endpoint: "/api/workflows/video/metadata/backup",
    fields: [
      { type: "path", id: "path", label: "Input video file" },
      { type: "path", id: "sidecar", label: "Sidecar file (optional)" },
    ],
    buildPayload: (values) => ({ path: values.path, sidecar: values.sidecar, output: "" }),
  },
  {
    id: "video-restore",
    category: "Video",
    label: "Metadata restore",
    endpoint: "/api/workflows/video/metadata/restore",
    fields: [
      { type: "path", id: "path", label: "Input video file" },
      { type: "path", id: "sidecar", label: "Sidecar file" },
      { type: "path", id: "output", label: "Output video file (optional)" },
    ],
    buildPayload: (values) => ({ path: values.path, sidecar: values.sidecar, output: values.output }),
  },
];
